Use new deployment agents
SkillsFundingAgency/das-shared-infrastructure pull request #66
Opened 2021-09-24 12:16 UTC by smehta-dfe

2021-09-24 14:16 UTC, jack-cloud-platform approved these changes

2021-09-24 14:30 UTC, jack-cloud-platform requested changes
Should this be a Deployment agent pool as it's a build?

2021-09-29 16:01 UTC, EwanNoble commented on azure-pipelines.yml
> +  - template: pipeline-templates/job/code-build.yml
There are no dotnet projects in this repository, what is this supposed to be building?

2021-09-29 16:01 UTC, EwanNoble commented on azure-pipelines.yml
> -  - script: |
Why are we deleting all of this?

2022-03-04 16:00 UTC, closed without merging